# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_model_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='model_products', to='Products.Model_Category'),
            preserve_default=False,
        ),
    ]
