# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 11:29
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20180424_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
