# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 06:47
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_auto_20180425_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_color',
        ),
        migrations.AlterField(
            model_name='product',
            name='available_size',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='productcolors',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='Products.Product'),
        ),
    ]
