# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_auto_20180425_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=39.99, max_digits=20),
        ),
    ]
