# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 11:59
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_product_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolors',
            name='available_color',
            field=colorfield.fields.ColorField(max_length=18),
        ),
    ]
