# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_auto_20180426_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
