# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_productimages_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='name',
        ),
    ]
