# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Gender',
            field=models.CharField(default='m', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Manufacturer',
            field=models.CharField(default='m', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Occassion',
            field=models.CharField(default='m', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Season',
            field=models.CharField(default='m', max_length=50),
            preserve_default=False,
        ),
    ]
